function labels = get_key_blend_scheme_labels()
    labels = {  'value alpha (open)', ...
                'Static alpha', ...  
                'Sample alpha (static)', ...
                'Mo and Karen', ...
                'CDC'};
end 