function all_blend_scheme_names = get_all_blend_scheme_names()
    all_blend_scheme_names = {'value alpha (open)', ...
                            'value alpha (closed)', ...
                            'safety value', ...
                            'Static alpha', ...  
                            'Sample alpha (static)', ...
                            'Min inv. alpha (static)', ...
                            'Triangle replan', ...
                            'Mo and Karen', ...
                            'CDC'};
end 