function key_blend_schemes = get_key_blend_schemes()
    key_blend_schemes = {'time_vary_alpha_open_loop', ...
                        'sample_safety_control', ...
                        'replan_safe_traj', ...
                        'none'}; 
end 
