function all_blend_schemes = get_all_blend_schemes()
    all_blend_schemes = {'time_vary_alpha_open_loop_safety_control', ...
                        'time_vary_alpha_closed_loop_safety_control', ...
                        'safety_value', ...
                        'safety_control', ...
                        'sample_safety_value', ...
                        'sample_safety_control', ...
                        'replan_waypoint', ....
                        'replan_safe_traj', ...
                        'none'}; 
end 