function metric_names = get_all_metric_names()
    metric_names = {
        'linear jerk', ...
        'angular jerk', ...
        'safety score', ...
        'dist_to_opt_traj', ...
        'timestamp', ...
        'num safety ctrls', ...
        'termination', ...
        'reached', ...
        'crashed', ...
        'tle', ...
        'error' ...
    }; 
end 