function labels = get_all_blend_scheme_labels()
    labels = {  'value alpha (open)', ...
                'value alpha (closed)', ...
                'safety value', ...
                'Static alpha', ...  
                'Sample alpha (static)', ...
                'Min inv. alpha (static)', ...
                'Triangle replan', ...
                'Mo and Karen', ...
                'CDC'};
end 