function all_blend_scheme_colors = get_all_blend_scheme_colors()
    all_blend_scheme_colors =   [1,0,0; ...
                                 0.9,0,0.5; ...
                                 0,0,1; ...
                                 0.2,0.1,0.9; ...
                                 0.2,0.9,0.1; ...
                                 0.6,0.1,0.5; ...
                                 0.7,0.5, 0.1; ...
                                 0.1,0.8,0.3;
                                 0.5,0.5,0.5];
end 